package com.duckblade.osrs.sailing.features.barracudatrials;

import com.duckblade.osrs.sailing.SailingConfig;
import com.duckblade.osrs.sailing.features.util.BarracudaTrialTracker;
import com.duckblade.osrs.sailing.features.util.SailingUtil;
import com.duckblade.osrs.sailing.module.PluginLifecycleComponent;
import com.google.common.collect.ImmutableSet;
import lombok.extern.slf4j.Slf4j;
import net.runelite.api.*;
import net.runelite.api.coords.LocalPoint;
import net.runelite.api.events.*;
import net.runelite.api.gameval.ObjectID;
import net.runelite.client.eventbus.Subscribe;
import net.runelite.client.ui.overlay.Overlay;
import net.runelite.client.ui.overlay.OverlayLayer;
import net.runelite.client.ui.overlay.OverlayPosition;
import net.runelite.client.ui.overlay.OverlayUtil;

import javax.inject.Inject;
import javax.inject.Singleton;
import java.awt.*;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Slf4j
@Singleton
public class LostCratesOverlay
	extends Overlay
	implements PluginLifecycleComponent
{
	private static final Set<Integer> LOST_CRATES_IDS = ImmutableSet.of(
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_1,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_2,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_3,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_4,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_5,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_6,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_7,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_8,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_9,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_10,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_11,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_12,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_13,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_14,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_15,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_16,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_17,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_18,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_19,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_20,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_21,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_22,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_23,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_24,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_25,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_26,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_27,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_28,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_29,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_30,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_31,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_32,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_33,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_34,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_35,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_36,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_37,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_38,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_39,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_40,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_41,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_42,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_43,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_44,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_45,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_46,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_47,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_48,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_49,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_50,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_51,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_52,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_53,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_54,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_55,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_56,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_57,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_58,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_59,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_60,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_61,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_62,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_63,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_64,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_65,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_66,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_67,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_68,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_69,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_70,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_71,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_72,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_73,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_74,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_75,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_76,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_77,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_78,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_79,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_80,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_81,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_82,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_83,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_84,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_85,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_86,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_87,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_88,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_89,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_90,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_91,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_92,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_93,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_94,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_95,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_96,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_1,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_2,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_3,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_4,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_5,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_6,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_7,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_8,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_9,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_10,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_11,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_12,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_13,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_14,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_15,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_16,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_17,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_18,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_19,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_20,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_21,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_22,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_23,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_24,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_25,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_26,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_27,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_28,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_29,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_30,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_31,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_32,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_33,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_34,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_35,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_36,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_37,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_38,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_39,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_40,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_41,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_42,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_43,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_44,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_45,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_46,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_47,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_48,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_49,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_50,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_51,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_52,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_53,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_54,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_55,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_56,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_1,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_2,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_3,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_4,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_5,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_6,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_7,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_8,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_9,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_10,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_11,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_12,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_13,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_14,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_15,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_16,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_17,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_18,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_19,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_20,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_21,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_22,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_23,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_24,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_25,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_26,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_27,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_28,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_29,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_30,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_31,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_32,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_33,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_34,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_35,
			ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_36
	);

	private final Client client;
	private final SailingConfig config;
	private final BarracudaTrialTracker trialTracker;

	private final Set<GameObject> lostCrates = new HashSet<>();
	private Color crateColor;

	@Inject
	public LostCratesOverlay(Client client, SailingConfig config, BarracudaTrialTracker trialTracker)
	{
		this.client = client;
		this.config = config;
		this.trialTracker = trialTracker;

		setPosition(OverlayPosition.DYNAMIC);
		setLayer(OverlayLayer.ABOVE_SCENE);
	}

	@Override
	public boolean isEnabled(SailingConfig config)
	{
		crateColor = config.barracudaHighlightLostCratesColor();
		return config.barracudaHighlightLostCrates();
	}

	@Override
	public void shutDown()
	{
		lostCrates.clear();
	}

	@Subscribe
	public void onWorldViewUnloaded(WorldViewUnloaded e)
	{
		if (e.getWorldView().isTopLevel())
		{
			lostCrates.clear();
		}
	}

	@Subscribe
	public void onGameObjectSpawned(GameObjectSpawned e)
	{
		GameObject o = e.getGameObject();
		if (LOST_CRATES_IDS.contains(o.getId()))
		{
			lostCrates.add(o);
		}
	}

	@Subscribe
	public void onGameObjectDespawned(GameObjectDespawned e)
	{
		lostCrates.remove(e.getGameObject());
	}

	@Override
	public Dimension render(Graphics2D g)
	{
		if (!SailingUtil.isSailing(client) || !config.barracudaHighlightLostCrates() || !trialTracker.isInTrial())
		{
			return null;
		}

		for (GameObject crate : lostCrates)
		{
			ObjectComposition def = SailingUtil.getTransformedObject(client, crate);
			if (def != null)
			{
				if (config.barracudaExpandHighlightLostCrates())
				{
					Polygon poly = Perspective.getCanvasTileAreaPoly(client, Objects.requireNonNull(LocalPoint.fromWorld(client, crate.getWorldLocation())), 4);

					if (poly != null)
					{
						OverlayUtil.renderPolygon(g, poly, crateColor);
					}
				}
				else
				{
					OverlayUtil.renderTileOverlay(g, crate, "", crateColor);
				}
			}
		}

		return null;
	}
}
